jQuery(document).ready(function($) {
	
	$.each(tabs_shortcode, function(id, attr) {
		$("#" + id).tabs( attr );
	});
	if ( location.hash ) {
		$('a[href="'+location.hash+'"]').trigger('click');
	}
});
//Responsive Tabs
jQuery(document).ready(function(e){if(t===undefined){var t={}}t.responsiveTabs=function(n){"use strict";t.currentPosition="tabs";var r=e(".nav-tabs.responsive"),i="",s="";if(n===undefined){n=["phone","tablet"]}e.each(n,function(){i+=" hidden-"+this;s+=" visible-"+this});e.each(r,function(){var t=e(this),n=t.find("li a"),r=e("<div></div>",{"class":"accordion responsive"+s,id:"collapse-"+t.attr("id")});e.each(n,function(){var n=e(this),i="",s=n.attr("class")===undefined?"":n.attr("class"),o="accordion-toggle",u=n.parent().attr("class")===undefined?"":n.parent().attr("class"),a="accordion-group";if(s.length>0){o+=" "+s}if(u.length>0){u=u.replace(/bactiveb/g,"");a+=" "+u;a=a.replace(/s{2,}/g," ");a=a.replace(/^s+|s+$/g,"")}if(n.parent().hasClass("active")){i=" in"}r.append(e("<div>").attr("class",a).html(e("<div>").attr("class","accordion-heading").html(e("<a>",{"class":o,"data-toggle":"collapse","data-parent":"#collapse-"+t.attr("id"),href:"#collapse-"+n.attr("href").replace(/#/g,""),html:n.html()}))).append(e("<div>",{id:"collapse-"+n.attr("href").replace(/#/g,""),"class":"accordion-body collapse"+i}).html(e("<div>").attr("class","accordion-inner").html(""))))});t.next().after(r);t.addClass(i);e(".tab-content.responsive").addClass(i)});t.checkResize();t.bindTabToCollapse()};t.checkResize=function(){"use strict";if(e(".accordion.responsive").is(":visible")===true&&t.currentPosition==="tabs"){t.toggleResponsiveTabContent();t.currentPosition="panel"}else if(e(".accordion.responsive").is(":visible")===false&&t.currentPosition==="panel"){t.toggleResponsiveTabContent();t.currentPosition="tabs"}};t.toggleResponsiveTabContent=function(){"use strict";var t=e(".nav-tabs.responsive");e.each(t,function(){var t=e(this).find("li a");e.each(t,function(){var t=e(this).attr("href").replace(/#/g,""),n="#"+t,r="#collapse-"+t,i=e(n).html(),s=e(r+" div:first-child").html();e(n).html(s);e(r+" div:first-child").html(i)})})};t.bindTabToCollapse=function(){"use strict";var t=e(".nav-tabs.responsive").find("li a"),n=e(".accordion.responsive").find(".accordion-body");t.on("shown",function(t){var n=e(e(t.target)[0].hash.replace(/#/,"#collapse-"));if(!n.hasClass("in")){n.addClass("in").height("auto")}if(t.relatedTarget){var r=e(e(t.relatedTarget)[0].hash.replace(/#/,"#collapse-"));r.removeClass("in").height("0px")}});n.on("shown",function(t){var n=e(t.target).context.id.replace(/collapse-/g,"#");e('a[href="'+n+'"]').tab("show")})};e(window).resize(function(){"use strict";t.checkResize()});t.responsiveTabs()})